### ISSUE TITLE
지금까지의 이슈 목록

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#106]
## 이슈 목록

- [ ] 창 width 일정 크기 이하로 줄여질때 프로필 nav바 위치 틀어짐
- [ ] 챗봇에 토큰 연동 해제할때 경고창 만들기
- [ ] 챗봇 목록에서 클릭해서 키웠을때 클릭안되는 부분도 클릭할 수 있는 것처럼 손가락 모양 으로 존재
- [x] 고정 메뉴로 이름 바꿧는데 경고창에는 [버튼형 리스트]로 나옴
- [ ] 키워드 부분 보기 어려움.. 보다 알기 쉽게 개선 필요.. (얘기 필요)
- [ ] 라인 오디오는 duration이 필요하다함.. 그러면 multer에서 주는 정보중 file 정보에 duration 있는지 확인해보기
- [ ] 버전 관리 - 배포, 불러오기 호버 생상 적용, 배포 누르면 alert 하기

**Comment by giraff** [comment]
[Update] ISSUE 4: 고정 메뉴로 이름 바꿨는데 경고창에는 [버튼형 리스트]로 나옴
=> [고정 메뉴]라고 표시되도록 수정

**Comment by Hanswind** [comment]
이슈 분리 위해 close
