### ISSUE TITLE
고정메뉴 main 부분 이슈

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#109]
- [x] 고정메뉴 만들고 다른거 클릭했다가 다시 클릭하면 요소설정창에서 고정메뉴 설정 값 안불러오는 문제

**Comment by giraff** [comment]
PersistentStatus.js의 input의 'keywords'  state를 이용하지 않고 직접 KeywordLink 로 접근.

keywords를 사용하는 방향으로 가야한다면 피드백 부탁드림. 아님 무시
