### ISSUE TITLE
챗봇 토큰 연동 해제 경고창 없음

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#111]
- [x] 챗봇에 토큰 연동 해제할때 경고창 만들기

**Comment by junyeongjang** [comment]
토큰 연동 경고창 뿐만 아니라, 라인은 한 키워드당 4개의 메세지만 전송가능합니다. 
한 키워드에 4개 이상의 요소를 넣을 때에는 경고창을 띄워야합니다.

**Comment by CHOIKEONWOO** [comment]
구현
