### ISSUE TITLE
DB에서 버튼 템플릿 양식 받아 적용

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#118]
- [x] 건우형 DB에 데이터 전송 
- [x] 라인 DB 연동
- [x] 텔레그램 DB 연동
- [x] 로컬에 DB 적용
- [x] ver 1.3 배포 후 테스트  
건우형이 JSON 양식 만든다음에 확인후 수행

**Comment by junyeongjang** [comment]
버튼 템플릿 라인에서 구현 완료
