### ISSUE TITLE
버튼템플릿 메인 만들기

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#119]
- [x] useableInfo (플랫폼 호환 여부) state에 버튼 템플릿 및 다른 템플릿들도 추가
- [x] Tab에서 '버튼 템플릿' 클릭시 메인에 무언가 띄우기
- [x] 라인 용 버튼템플릿 인터페이스 제작
- [x] 텔레그램 용 버튼템플릿 인터페이스 제작
- [ ] 버튼 템플릿은 한 키워드 당 하나

**Comment by giraff** [comment]
텔레그램은 버튼 템플릿을 사용할 수 없는데 어떤 식으로 표시할까요

**Comment by CHOIKEONWOO** [comment]
이미지
텍스트
텍스트
로 구현해주세요

**Comment by giraff** [comment]
확인했습니다!
