### ISSUE TITLE
오디오 duration 관련 문제

### ISSUE THREAD

**Issue by junyeongjang** [Hanswind/EZ.ai#125]
- [x] req.file의 size에 duration 값을 넣어놨음. 건우형이 DB에 넣어야함
- [x] DB에 값이 들어가면, 라인에서 실제로 작동하는지 내가 테스트 해야함
- [x] m4a 파일은 아직 duration이 작동하는지 실험 안해봤음. 실험해봐야함

**Comment by CHOIKEONWOO** [comment]
DB에 size 기록
