### ISSUE TITLE
버튼리스트 이미지 css 수정

### ISSUE THREAD

**Issue by junyeongjang** [Hanswind/EZ.ai#133]
- 버튼 리스트에 이미지를 올리면 화면을 다 가려버리는 현상이 발생함

- [x] css 수정

**Comment by Hanswind** [comment]
일단 임시방편으로 수리 했지만, 
추후 cover, contain 속성에 따라 이미지에 적용 css 다르게 설정 필요.
(리액트 js 파일 내에서 값에 따라 css 다르게 적용하는 방법 사용 하기)
