### ISSUE TITLE
line message api - 버튼 템플릿 문제 

### ISSUE THREAD

**Issue by junyeongjang** [Hanswind/EZ.ai#135]
{
   "type":"postback",
   "label":"Buy",
   "data":"action=buy&itemid=111",
   "text":"Buy"
}

- 버튼 템플릿 postback의 action 내부 양식임 
- lable은 버튼명, text는 다시 메세지가 입력되는 내용
- [x] 건우형 DB에 text추가
- [x] 장준영 라인에 적용
- [x] 창희 프론트에 입력폼 추가

**Comment by Hanswind** [comment]
현재 keyword 선택하면 data로 매핑되는 방식인데, 이거 그냥 data에 있는 값 text로 복사하면 안되나? 
그래고 postback 안쓴다해도 챗봇에 type postback으로 넣고 data에 값 넣고 전송하면 오류 발생 안하면 위 방식대로 해도 될꺼같은데 준영 확인점 @junyeongjang

**Comment by junyeongjang** [comment]
지금 data에 값을 넣어주는 곳이 있어 ? 확인해보니깐 lable, uri에만 값을 넣을 수 있는 걸로 보여 @Hanswind

**Comment by CHOIKEONWOO** [comment]
label이랑 같게 text추가함

**Comment by junyeongjang** [comment]
> label이랑 같게 text추가함

label 값이랑 text 값이랑 같게 하지 말고, 입력을 따로 받아서 DB에 넣어야되는거 아니야 ?  label 값 text 값 같이 하는건 뒤에서 처리하면 되는데, 창희가 따로 받아야된다 그래서

**Comment by CHOIKEONWOO** [comment]
> > label이랑 같게 text추가함
> 
> label 값이랑 text 값이랑 같게 하지 말고, 입력을 따로 받아서 DB에 넣어야되는거 아니야 ? label 값 text 값 같이 하는건 뒤에서 처리하면 되는데, 창희가 따로 받아야된다 그러던데 @CHOIKEONWOO

![image](https://user-images.githubusercontent.com/46857207/87430586-64c35f00-c620-11ea-95ac-db9b19363eab.png)
이게 
![image](https://user-images.githubusercontent.com/46857207/87430657-7c024c80-c620-11ea-85bd-e847996fd783.png)
이렇게 JSON으로 바뀌는데

**Comment by CHOIKEONWOO** [comment]
키워드 선택하면 data에 값이 넣어지는데 
text칸 없어도 되는거 아니야?

**Comment by junyeongjang** [comment]
> 키워드 선택하면 data에 값이 넣어지는데
> text칸 없어도 되는거 아니야?

ㅇㅇ 만약 data에 값 넣어지면 text 추가 안해도 되는거 맞아 
내일 TEST 해볼게 
정확이 data 값이 왜 필요한지 알아볼게

**Comment by Hanswind** [comment]
> 지금 data에 값을 넣어주는 곳이 있어 ? 확인해보니깐 label, uri에만 값을 넣을 수 있는 걸로 보여 @Hanswind , data에 값을 넣을 수 있으면 창희 너가 말한대로 진행할 수 있어.

저거 action 버튼에서 키워드 선택한뒤에 키워드 선택하면 해당 키워드 string이 data 영역에 들어가
data 값으로 사용하면 돼.

**Comment by junyeongjang** [comment]
> > 지금 data에 값을 넣어주는 곳이 있어 ? 확인해보니깐 label, uri에만 값을 넣을 수 있는 걸로 보여 @Hanswind , data에 값을 넣을 수 있으면 창희 너가 말한대로 진행할 수 있어.
> 
> 저거 action 버튼에서 키워드 선택한뒤에 키워드 선택하면 해당 키워드 string이 data 영역에 들어가
> data 값으로 사용하면 돼.

ㅇㅋㅇㅋ 확인
