### ISSUE TITLE
버튼 템플릿 이미지 업로드 이슈

### ISSUE THREAD

**Issue by Hanswind** [Hanswind/EZ.ai#142]
- [x] 버튼 템플릿 이미지 올리고 다시 다른 이미지 올릴려고 클릭하면 에러 발생 @CHOIKEONWOO 
- [x] 이거 고치면 이미지 업로드 안하고 색만 바꿧을때 이미지 깨짐 현상 개선 - 투명 이미지 적용 @Hanswind

**Comment by CHOIKEONWOO** [comment]
버그 수정

**Comment by Hanswind** [comment]
에러 수정된거에요?
이미지 넣고 다시 이미지 클릭하니까 똑같은 오류 뜨는데
(TypeError: Cannot read property 'click' of null)
