### ISSUE TITLE
데이터 마케팅 및 그로쓰 해킹을 위한 데이터 생성 

### ISSUE THREAD

**Issue by junyeongjang** [Hanswind/EZ.ai#154]
- 우리가 키워드를 통해 추출할 데이터는 어떠한 주제의 챗봇에서 어떤 키워드를 사용했는지 분석하는 것 입니다.

- 만약에 상명대학교라는 챗봇에서 학식, 학사정보, 동아리 키워드를 많이 사용했다면, 다음에 대학교 챗봇을 만드는 사용자에게 학식, 학사정보, 동아리라는 키워드들이 들어있는 템플릿을 제공해줄 수 있겠죠 ?

- 키워드 데이터를 30개 씩 파일로 만들어서 올려주세요. 다른 분과 중복되어도 좋습니다.
ex){ keyword:"학사정보"}, {keyword:"독서 동아리"} 등등등

- 아까 회의에서는 안에 type이야기도 했지만, type은 필요없을 것 같습니다.

**우리가 추출할 데이터** 
- 어떤 챗봇에서 어떤 키워드들을 가장 많이 사용했느냐?

- [x]  테스트 데이터 제작 완료 @Hanswind
- [x]  테스트 데이터 제작 완료 @giraff 
- [x]  테스트 데이터 제작 완료 @CHOIKEONWOO 
- [x]  테스트 데이터 제작 완료 @junyeongjang

**Comment by junyeongjang** [comment]
- 실제 데이터를 받아오는 과정은 로그 서버를 따로 구축할 예정입니다.
- 웹서버 -> 로그 서버 (로그 전송) 
- 로그 서버는 데이터를 추출(파싱)하고 분석하는 역할을 할 예정입니다.

**Comment by Hanswind** [comment]
{ keyword: "열람실"},
{ keyword: "학사일정"},
{ keyword: "학사공지"},
{ keyword: "도서관"},
{ keyword: "상명대학교"},
{ keyword: "이캠퍼스"},
{ keyword: "e-campus"},
{ keyword: "샘물"},
{ keyword: "수강신청"},
{ keyword: "장바구니"},
{ keyword: "피어오름"},
{ keyword: "졸업"},
{ keyword: "휴학"},
{ keyword: "학점"},
{ keyword: "복수전공"},
{ keyword: "사회봉사"},
{ keyword: "전공"},
{ keyword: "교양필수"},
{ keyword: "교양선택"},
{ keyword: "학과"},
{ keyword: "과사"},
{ keyword: "스뮤"},
{ keyword: "분반"},
{ keyword: "학식"},
{ keyword: "안다미로"},
{ keyword: "7016"},
{ keyword: "집회정보"},
{ keyword: "학교정보"},
{ keyword: "교수"},
{ keyword: "장학금"},
{ keyword: "취업진로센터"},
{ keyword: "학생회"},
{ keyword: "단과대"},
{ keyword: "부전공"},
{ keyword: "계적학기"},
{ keyword: "전과"},
{ keyword: "사슴"},
{ keyword: "졸업요건"},
{ keyword: "강의"},
{ keyword: "시간표"},
{ keyword: "연강"},
{ keyword: "음식점"},
{ keyword: "전공심화"},
{ keyword: "전공선택"},
{ keyword: "수강인원"},
{ keyword: "국가장학금"},
{ keyword: "근로"},
{ keyword: "과목"},
{ keyword: "학술정보관"},
{ keyword: "공지사항"},
{ keyword: "증명서"},
{ keyword: "출결"},
{ keyword: "성적조회"},
{ keyword: "교육과정"},
{ keyword: "단과대"},
{ keyword: "학교식당"},
{ keyword: "미래백년관"},
{ keyword: "밀레니엄관"},
{ keyword: "상담"},
{ keyword: "비교과"},
{ keyword: "현장실습"},
{ keyword: "학생생활관"},
{ keyword: "공학인증"},
{ keyword: "교과과정"},
{ keyword: "방학"},
{ keyword: "sm-class"},
{ keyword: "자료실"},
{ keyword: "e-포토폴리오"},
{ keyword: "사이트맵"},
{ keyword: "등록금"}

**Comment by giraff** [comment]
{ keyword:"공지사항"}
{ keyword:"학사운영"}
{ keyword:"교내일정"}
{ keyword:"장학금"}
{ keyword:"국제교류"}
{ keyword:"병역"}
{ keyword:"예비군"}
{ keyword:"전공"}
{ keyword:"교양"}
{ keyword:"기숙사"}
{ keyword:"식단안내"}
{ keyword:"성적안내"}
{ keyword:"수강신청"}
{ keyword:"학점관리"}
{ keyword:"복학"}
{ keyword:"휴학"}
{ keyword:"복수전공"}
{ keyword:"전과"}
{ keyword:"편입"}
{ keyword:"교내번호"}
{ keyword:"입학안내"}
{ keyword:"졸업안내"}
{ keyword:"졸업요건"}
{ keyword:"SNS"}
{ keyword:"문서양식"}
{ keyword:"학생증발급"}
{ keyword:"학자금대출"}
{ keyword:"도서관"}
{ keyword:"교내봉사"}
{ keyword:"사회봉사"}
{ keyword:"연합동아리"}
{ keyword:"중앙동아리"}
{ keyword:"공모전"}
{ keyword:"교내채용정보"}
{ keyword:"학생상담"}
{ keyword:"취업프로그램"}
{ keyword:"캠퍼스"}
{ keyword:"사범대"}
{ keyword:"융합공과대"}
{ keyword:"경영경제대학"}
{ keyword:"문화예술대"}
{ keyword:"계당교양교육원"}
{ keyword:"학점은행제"}
{ keyword:"평생교육원"}
{ keyword:"미대"}
{ keyword:"체대"}
{ keyword:"역사콘텐츠"}
{ keyword:"국가안보학과"}
{ keyword:"총학"}
{ keyword:"부전공"}
{ keyword:"다전공"}
{ keyword:"심화전공"}
{ keyword:"조기졸업"}
{ keyword:"여름방학"}
{ keyword:"멘토링"}
{ keyword:"튜터링"}
{ keyword:"비교과프로그램"}
{ keyword:"대학원"}
{ keyword:"버스"}
{ keyword:"교통"}
{ keyword:"교수"}
{ keyword:"어학연수"}
{ keyword:"국제학생"}
{ keyword:"소모임"}
{ keyword:"공학인증"}
{ keyword:"현장체험"}
{ keyword:"특강"}
{ keyword:"커뮤니티"}
{ keyword:"주변식당"}
{ keyword:"주변카페"}

**Comment by CHOIKEONWOO** [comment]
{ keyword: "학사일정"},
{ keyword: "수강신청"},
{ keyword: "장바구니"},
{ keyword: "공지사항"},
{ keyword: "학식메뉴"},
{ keyword: "동아리"},
{ keyword: "교내행사"},
{ keyword: "축제"},
{ keyword: "과사무실"},
{ keyword: "기숙사"},
{ keyword: "열람실"},
{ keyword: "이캠퍼스"},
{ keyword: "교통편"},
{ keyword: "배차시간"},
{ keyword: "캠퍼스지도"},
{ keyword: "열람실"},
{ keyword: "등록금"},
{ keyword: "장학금"},
{ keyword: "도서관"},
{ keyword: "프린트"},
{ keyword: "주변식당"},
{ keyword: "출결"},
{ keyword: "출결어플"},
{ keyword: "졸업"},
{ keyword: "졸업이수학점"},
{ keyword: "조기졸업"},
{ keyword: "시간표"},
{ keyword: "시험일정"},
{ keyword: "봉사"},
{ keyword: "공학인증"},
{ keyword: "휴게실"},
{ keyword: "보건소"},
{ keyword: "날씨"},
{ keyword: "취업"},
{ keyword: "학생증"},
{ keyword: "증명서"},
{ keyword: "복수전공"},
{ keyword: "다전공"},
